ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS dni VARCHAR(8) UNIQUE;
ALTER TABLE agentes ADD COLUMN IF NOT EXISTS qr_code TEXT UNIQUE;
ALTER TABLE agentes ADD COLUMN IF NOT EXISTS qr_activo BOOLEAN DEFAULT TRUE;
